import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Login
    'login.title': '知壑 (WisVale)',
    'login.subtitle': '深度学习 · 智慧整理 · 考点击破',
    'login.studentId': '学号',
    'login.nickname': '昵称',
    'login.login': '进入系统',
    'login.demo': '演示模式',
    'login.error.id': '请输入学号',
    'login.error.nickname': '请输入昵称',
    'login.error.notAllowed': '该学号不在允许名单中，请联系管理员',
    'login.loading': '正在进入...',
    'login.configNotReady': 'Firebase 配置尚未就绪',
    'login.enableAnonymous': '请在 Firebase 控制台启用匿名登录：',
    'login.configStep1': '进入 Firebase 控制台 -> Authentication',
    'login.configStep2': '选择 "Sign-in method"',
    'login.configStep3': '启用 "Anonymous"',
    'login.goToConfig': '前往配置',
    'login.permissionError': '权限错误: {message}',
    'login.notAuthorized': '该学号未获授权，请联系管理员',
    'login.profileError': '个人资料初始化失败: {message}',
    'login.loginFail': '登录失败，请重试',
    'login.help': '帮助文档',
    'login.authorizedOnly': '仅限授权用户访问',
    'login.idPlaceholder': '输入学号',
    'login.demoDesc': '演示模式：学号 {adminId} 为管理员。',

    // Dashboard
    'nav.home': '首页',
    'nav.knowledge': '知识库',
    'nav.upload': '录入题目',
    'nav.leaderboard': '英雄榜',
    'nav.admin': '管理后台',
    'nav.logout': '退出',
    'dashboard.welcome': '欢迎回来',
    'dashboard.search': '搜索题目内容...',
    'dashboard.search.placeholder': '搜索题目内容、编号、来源...',
    'dashboard.filter.all': '全部领域',
    'dashboard.batchCollect': '批量收藏知识点',
    'dashboard.noQuestions': '暂无题目，快去录入吧！',
    'dashboard.deleteConfirm': '确认',
    'dashboard.deleteCancel': '取消',
    'dashboard.filters': '多维筛选',
    'dashboard.resetFilters': '重置所有筛选',
    'dashboard.includeMode': '包含模式',
    'dashboard.excludeMode': '排除模式',
    'dashboard.selectAll': '全选当前',
    'dashboard.clearSelection': '清空选择',
    'dashboard.batchInputIds': '批量输入题号 (U0001.U0002)...',
    'dashboard.batchSelect': '批量选择',
    'dashboard.sort.latest': '最新',
    'dashboard.sort.earliest': '最早',
    'dashboard.sort.random': '随机',
    'dashboard.adminConsole': '管理员控制台',
    'dashboard.questionBank': '大生物题库',
    'dashboard.totalQuestions': '题库总量',
    'dashboard.selectedQuestions': '已选题目',
    'dashboard.selected': '已选 {count} 题',
    'dashboard.distribution': '选题分布',
    'dashboard.totalSelected': '共计 {count} 道题目',
    'dashboard.copyIds': '复制题号',
    'dashboard.generatePaper': '生成试卷',
    'dashboard.paperTitle': '试卷标题',
    'dashboard.paperTitlePlaceholder': '输入试卷标题...',
    'dashboard.generateConfirm': '确认生成',
    'dashboard.nickname': '昵称',
    'dashboard.batchActions': '批量操作',
    'dashboard.inputTag': '输入标签...',
    'dashboard.addTag': '打标',
    'dashboard.batchCollectKps': '批量收藏知识点',
    'dashboard.filter.field': '学科领域',
    'dashboard.filter.difficulty': '难度',
    'dashboard.filter.source': '来源',
    'dashboard.filter.type': '类型',
    'dashboard.filter.uploader': '上传者',
    'dashboard.filter.personalTags': '个人标签',
    'dashboard.filter.publicTags': '公共标签',
    'dashboard.welcome.subtitle': '{name}，今天准备攻克哪一类难题？',

    // KnowledgeBase
    'kb.title': '我的知识库',
    'kb.subtitle': '管理您的个人生物考点体系',
    'kb.tab.level1': '一级',
    'kb.tab.level2': '二级',
    'kb.tab.level3': '三级',
    'kb.tab.mastered': '已掌握',
    'kb.tab.summary': '学习总结',
    'kb.search': '搜索知识点...',
    'kb.import': '批量导入题号',
    'kb.importPlaceholder': '输入题号，用逗号或换行分隔',
    'kb.importBtn': '导入',
    'kb.empty': '该级别暂无知识点',
    'kb.summary.total': '目前已录入 {count} 个知识点。',
    'kb.summary.mastered': '其中 {count} 个已完全掌握。',
    'kb.summary.suggestion.improve': '您有 {count} 个知识点停留在一级，建议今日至少将 5 个知识点提升至二级。',
    'kb.summary.suggestion.good': '您的知识体系非常稳健，继续保持！',
    'kb.summary.ai.loading': 'Qwen 正在深度分析您的知识体系...',
    'kb.summary.ai.placeholder': '点击刷新按钮生成 AI 总结',
    'kb.summary.ai.fail': 'AI 总结生成失败，请稍后重试。',
    'kb.summary.ai.networkError': '网络错误，请检查连接。',
    'kb.aiAnalysis': 'AI 深度分析报告',
    'kb.distribution': '知识分布',
    'kb.suggestion': '今日建议',

    // Upload
    'upload.title': '录入生物题目',
    'upload.subtitle': '支持图片识别与 AI 自动整理考点',
    'upload.step1': '上传题面',
    'upload.step2': '上传解析 (可选)',
    'upload.step3': '确认题目信息',
    'upload.step4': '生成知识点',
    'upload.field': '所属领域',
    'upload.source': '题目来源',
    'upload.difficulty': '难度标签',
    'upload.type': '题目类型',
    'upload.content': '题目内容',
    'upload.explanation': '题目解析',
    'upload.submit': '提交题目',
    'upload.questionId': '题号',
    'upload.optional': '选填',
    'upload.required': '必须',
    'upload.autoOcr': '自动识别',
    'upload.clickOrDrag': '点击或拖拽图片',
    'upload.releaseToSelect': '放开以选择',
    'upload.camera': '拍照上传',
    'upload.gallery': '图库选择',
    'upload.remove': '移除',
    'upload.generatingKps': '正在生成知识点...',
    'upload.confirmKps': '确认知识点',
    'upload.aiAnalyzing': '开始ai分析',
    'upload.answer': '解析',
    'upload.ocrProcessing': '正在识别文字...',
    'detail.back': '返回',
    'detail.edit': '编辑',
    'detail.content': '题目内容',
    'detail.answer': '参考答案',
    'detail.noAnswer': '暂无答案',
    'detail.explanation': '详细解析',
    'detail.noExplanation': '暂无解析',
    'detail.aiKps': 'AI 提取知识点',
    'detail.categoryInfo': '分类信息',
    'detail.notSet': '未设置',
    'detail.metadata': '元数据',
    'detail.uploader': '上传者',
    'detail.uploadTime': '上传时间',
    'detail.image': '题目图片',
    'detail.notFound': '未找到该题目',
    'detail.backToBank': '返回题库',
    'detail.unknownUser': '未知用户',

    // Enums
    'enum.diff.难题': '难题',
    'enum.diff.易错题': '易错题',
    'enum.difficulty.难题': '难题',
    'enum.difficulty.易错题': '易错题',
    'enum.type.概念题': '概念题',
    'enum.type.计算题': '计算题',
    'enum.type.材料题': '材料题',
    'enum.field.生物化学': '生物化学',
    'enum.field.细胞生物学': '细胞生物学',
    'enum.field.植物学': '植物学',
    'enum.field.动物学': '动物学',
    'enum.field.微生物学': '微生物学',
    'enum.field.动物生理学': '动物生理学',
    'enum.field.植物生理学': '植物生理学',
    'enum.field.其他': '其他',
    'enum.source.猿辅导': '猿辅导',
    'enum.source.汇智启航': '汇智启航',
    'enum.source.北斗学友': '北斗学友',
    'enum.source.联赛题': '联赛题',
    'enum.source.国赛题': '国赛题',
    'enum.source.愿程': '愿程',
    'enum.source.其他': '其他',

    // Common
    'common.confirm': '确认',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.redo': '重做',
    'common.save': '保存',
    'common.loading': '加载中...',
    'common.success': '操作成功',
    'common.error': '操作失败',
    'common.back': '返回',
    'common.next': '下一步',
    'common.finish': '完成',
    'common.all': '全部',
    'common.none': '无',

    // Leaderboard
    'leaderboard.title': '英雄榜',
    'leaderboard.subtitle': '见证每一位生物学霸的成长轨迹',
    'leaderboard.tab.questions': '录题榜',
    'leaderboard.tab.kps': '知识点榜',
    'leaderboard.tab.answers': '答题榜',
    'leaderboard.tab.tokens': 'Token 消耗榜',
    'leaderboard.rank': '排名',
    'leaderboard.user': '用户',
    'leaderboard.score': '得分',
    'leaderboard.fullList': '完整榜单',
    'leaderboard.activeUsers': '{count} 位活跃用户',
    'leaderboard.anonymous': '匿名用户',
    'leaderboard.champion': '冠军贡献者',
    'leaderboard.runnerUp': '亚军贡献者',
    'leaderboard.thirdPlace': '季军贡献者',
    'leaderboard.unit.question': '题',
    'leaderboard.unit.kp': '个',
    'leaderboard.unit.answer': '次',
    'leaderboard.unit.token': 'tokens',
    'leaderboard.label.questions': '录入题目数',
    'leaderboard.label.kps': '录入知识点数',
    'leaderboard.label.answers': '答题次数',
    'leaderboard.label.tokens': 'Token 消耗量',
    'leaderboard.noData': '暂无排行数据',
    'leaderboard.role.admin': '管理员',
    'leaderboard.role.student': '正式成员',
    'leaderboard.howToEarn': '如何赚取积分？',
    'leaderboard.earn.upload': '录入一道新题目',
    'leaderboard.earn.selected': '题目被他人选中组卷',
    'leaderboard.earn.generate': '生成并打印一份试卷',
    'leaderboard.whatIsPoints': '积分有什么用？',
    'leaderboard.pointsDesc': '积分是系统贡献度的唯一衡量标准。',

    // Answer Page
    'answer.title': '知识点挑战',
    'answer.subtitle': '巩固记忆，攻克难点',
    'answer.inputPlaceholder': '请输入您的回答...',
    'answer.submit': '提交批改',
    'answer.evaluating': 'AI 正在批改...',
    'answer.pass': '恭喜！回答正确',
    'answer.fail': '遗憾！回答有误',
    'answer.keepLevel': '我依然很棒',
    'answer.next': '下一题',
    'answer.evalFail': '批改失败，请重试',
    'answer.noKps': '没有找到需要答题的知识点',
    'answer.progress': '进度',

    // Admin
    'admin.title': '账户管理中心',
    'admin.subtitle': '管理所有授权学号及已注册用户信息',
    'admin.batchImport': '批量导入',
    'admin.cancelBatch': '取消批量',
    'admin.inputStudentId': '输入新学号授权...',
    'admin.addAuth': '新增授权',
    'admin.batchPlaceholder': '格式: 姓名:学号。姓名:学号。',
    'admin.executeBatch': '执行批量导入',
    'admin.table.idNickname': '学号 / 昵称',
    'admin.table.status': '状态',
    'admin.table.role': '权限角色',
    'admin.table.time': '注册/授权时间',
    'admin.table.action': '操作',
    'admin.status.registered': '已注册',
    'admin.status.unregistered': '未注册',
    'admin.role.admin': '管理员',
    'admin.role.student': '普通学生',
    'admin.role.permanent': '系统永久管理员',
    'admin.action.removeConfirm': '确认移除?',
    'admin.action.yes': '是',
    'admin.action.no': '否',
    'admin.noData': '暂无账户数据',
    'admin.loading': '正在加载管理数据...',
    'admin.birthday.title': '生日主题设置',
    'admin.birthday.subtitle': '配置全站庆生模式',
    'admin.birthday.slogan': '生日标语',
    'admin.birthday.placeholder': '输入生日标语...',
    'admin.qidan.title': '七单紫主题设置',
    'admin.qidan.subtitle': '配置全站七单紫模式',
    'admin.qidan.slogan': '自定义标语',
    'admin.qidan.placeholder': '输入自定义标语...',
    'admin.saveConfig': '保存配置',
    'admin.enabled': '已启用',
    'admin.disabled': '已禁用',
    'admin.permanentAdminError': '该账户为永久管理员，不可更改权限。',
    'admin.permanentAdmin.editId': '修改永久管理员学号',
    'admin.permanentAdmin.newIdPlaceholder': '输入新的学号...',
    'admin.permanentAdmin.updateBtn': '更新学号',
    'admin.permanentAdmin.confirmTitle': '确认修改学号？',
    'admin.permanentAdmin.confirmDesc': '修改后，您需要使用新学号重新登录。',
    'admin.demoError': '演示模式下无法保存设置',
    'admin.saveSuccess': '设置已更新！',
    'admin.saveFail': '保存失败',
    'admin.batchSuccess': '批量导入成功！',
    'admin.batchFail': '导入失败，请检查格式。',
    'admin.addFail': '添加失败，请检查网络或 Firebase 配置。',

    // Edit Question
    'edit.title': '修改题目信息',
    'edit.subtitle': '题目编辑 · EDIT QUESTION',
    'edit.uploaderInfo': '由 {uploader} 上传于 {date}',
    'edit.backToBank': '返回题库',
    'edit.imagePreview': '题目原图预览',
    'edit.noImage': '该题目无附图',
    'edit.ocrIndex': 'OCR 识别内容 (搜索索引)',
    'edit.ocrPlaceholder': 'OCR 识别出的文字将显示在这里...',
    'edit.fieldLabel': '学科领域 (可多选)',
    'edit.sourceLabel': '题目来源',
    'edit.sourceDetailLabel': '来源详细描述',
    'edit.sourceDetailPlaceholder': '例如：2024年海淀区期中考试第15题',
    'edit.difficultyLabel': '难度分类 (可多选)',
    'edit.typeLabel': '题目类型',
    'edit.publicTagsLabel': '公共标签 (英文逗号分隔)',
    'edit.publicTagsPlaceholder': '例如：必修一, 重点, 易错',
    'edit.answerLabel': '参考答案',
    'edit.answerPlaceholder': '输入正确答案...',
    'edit.explanationLabel': '详细解析',
    'edit.explanationPlaceholder': '输入题目解析过程...',
    'edit.saveBtn': '保存修改',
    'edit.loading': '正在加载题目数据...',
    'edit.notExist': '题目不存在',
    'edit.noPermission': '您没有权限编辑此题目',
    'edit.loadFail': '加载失败',
    'edit.saveSuccessDemo': '演示模式：修改已模拟保存。',

    // Knowledge Base Extra
    'kb.level.masteredTitle': '已掌握知识点',
    'kb.level.masteredDesc': '您已完全掌握的知识点列表',
    'kb.level.searchPlaceholder': '搜索知识点...',
    'kb.level.allFields': '全部领域',
    'kb.level.newTab': '在新窗口打开',
    'kb.level.exportPdf': '打印 / 导出 PDF',
    'kb.level.levelName': '第 {level} 级知识点',
    'kb.level.levelDesc': '当前处于第 {level} 阶段的知识点',
    'kb.level.batchImportTitle': '批量导入题号',
    'kb.level.batchImportPlaceholder': '输入题号 (如: U0001 U0002)',
    'kb.level.import': '导入',
    'kb.level.title': '知识点级别',
    'kb.level.printTitle': '知识点清单',
    'kb.level.noMatch': '未找到匹配知识点',
    'kb.level.startAnswering': '开始答题',
    'kb.printCount': '题目数量',
    'kb.printVersion': '版本',
    'kb.printVersionA': '仅知识点版',
    'kb.printVersionB': '知识点+答案版',
    'kb.printTooltip': '在新窗口打开以获得更好的打印效果',
    'kb.exportTooltip': '打印 / 导出 PDF',
    'kb.batchImportTitle': '批量导入题号',
    'kb.batchImportPlaceholder': '输入题号 (如: U0001 U0002)',
    'kb.batchImportBtn': '导入',
    'kb.printTitle': '知识点清单',
    'kb.printDate': '生成日期',
    'kb.printMasteredTitle': '已掌握知识点清单',
    'kb.summary.distribution': '知识分布分析',
    'kb.summary.report': '整体分析报告',
    'kb.summary.weakness': '薄弱科目建议',
    'kb.summary.strengthen': '需加强',
    'kb.summary.progress': '学习进度',
    'kb.summary.level1': '一级 (待学习)',
    'kb.summary.level2': '二级 (复习中)',
    'kb.summary.level3': '三级 (冲刺中)',
    'kb.summary.level4': '已掌握',

    // Upload Extra
    'upload.kpExists': '知识点“{title}”已存在于您的知识库中。',
    'upload.kpCollected': '已将“{title}”收藏至知识点库！',
    'upload.kpCollectFail': '收藏失败，请重试。',
    'upload.duplicateQuestion': '检测到题库中已存在相同题目，正在跳转到详情页...',
    'upload.ocrFail': '图片处理或 AI 识别失败，请手动输入内容。',
    'upload.noImageError': '请先上传题目文字图片',
    'upload.noContentError': '题目内容不能为空。',
    'upload.noKpError': '请至少确认一个知识点。',
    'upload.tooManyKpsError': '知识点不能超过3个。',
    'upload.submitSuccess': '题目已成功录入！',
    'upload.submitFail': '提交失败，请重试。',
    'upload.addKp': '添加知识点',
    'upload.aiHint': '如要上传解析，请一并上传再点击ai分析',
    'kb.level.confirmMaster': '确认掌握',
    'kb.level.questionId': '题号',
    'paper.mode.paper': '试卷模式',
    'paper.mode.answer': '答案模式',
    'paper.mode.explanation': '解析模式',
    'paper.newTab': '新窗口打开',
    'paper.printBtn': '打印 / 导出',
    'paper.backToSetup': '返回设置',
    'paper.printTip': '提示：请在打印设置中勾选“背景图形”以获得最佳效果',
    'paper.total': '道题目',
    'paper.countLabel': '题目数量',
    'paper.title': '试卷生成器',
    'paper.subtitle': '根据已选题目生成专业排版的试卷',
    'paper.status.title': '生成状态',
    'paper.status.ready': '已选择 {count} 道题目，准备就绪',
    'paper.status.empty': '尚未选择题目',
    'paper.status.continue': '继续生成',
    'paper.status.goSelect': '去选题',
    'paper.inputTitle': '试卷主标题',
    'paper.inputTitlePlaceholder': '例如：2024年生物期末模拟测试',
    'paper.layoutOptions': '排版选项',
    'paper.option.autoNumber': '自动编号',
    'paper.option.studentInfo': '学生信息栏',
    'paper.option.a4Size': 'A4 纸张尺寸',
    'paper.previewExport': '预览与导出',
    'paper.enterPreview': '进入预览模式',
    'paper.tipTitle': '温馨提示',
    'paper.tipDesc': '生成的试卷将自动包含题目内容、来源等信息。您可以选择不同的模式（试卷/答案/解析）进行打印。',
    'paper.selectedCount': '已选题目',
    'paper.noContent': '暂无题目内容',
    'paper.noAnswer': '暂无答案',
    'paper.noExplanation': '暂无解析',
    // Layout
    'layout.updateNicknameFail': '更新昵称失败，请重试。',
    'layout.fullscreen.exit': '退出全屏',
    'layout.fullscreen.enter': '全屏模式',
    'layout.viewMode.title': '视图模式',
    'layout.viewMode.auto': '自动',
    'layout.viewMode.mobile': '手机',
    'layout.viewMode.desktop': '桌面',
    'layout.nickname.placeholder': '设置昵称...',
    'layout.status.online': '在线',
    'layout.feedback': '问题反馈',
    'layout.demoMode.title': '演示模式',
    'layout.demoMode.desc': '数据不会被保存',
  },
  en: {
    // Login
    'login.title': 'WisVale (知壑)',
    'login.subtitle': 'Deep Learning · Smart Organization · Key Points',
    'login.studentId': 'Student ID',
    'login.nickname': 'Nickname',
    'login.login': 'Enter System',
    'login.demo': 'Demo Mode',
    'login.error.id': 'Please enter Student ID',
    'login.error.nickname': 'Please enter Nickname',
    'login.error.notAllowed': 'Student ID not allowed, contact admin',
    'login.loading': 'Entering...',
    'login.configNotReady': 'Firebase configuration not ready',
    'login.enableAnonymous': 'Please enable Anonymous sign-in in Firebase Console:',
    'login.configStep1': 'Go to Firebase Console -> Authentication',
    'login.configStep2': 'Select "Sign-in method"',
    'login.configStep3': 'Enable "Anonymous"',
    'login.goToConfig': 'Go to Config',
    'login.permissionError': 'Permission error: {message}',
    'login.notAuthorized': 'Student ID not authorized, contact admin',
    'login.profileError': 'Profile initialization failed: {message}',
    'login.loginFail': 'Login failed, please try again',
    'login.help': 'Help Docs',
    'login.authorizedOnly': 'Authorized Access Only',
    'login.idPlaceholder': 'Enter your student ID',
    'login.demoDesc': 'Demo mode: Student ID {adminId} is admin.',

    // Dashboard
    'nav.home': 'Home',
    'nav.knowledge': 'Knowledge Base',
    'nav.upload': 'Upload Question',
    'nav.leaderboard': 'Leaderboard',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    'dashboard.welcome': 'Welcome back',
    'dashboard.search': 'Search questions...',
    'dashboard.search.placeholder': 'Search content, ID, source...',
    'dashboard.filter.all': 'All Fields',
    'dashboard.batchCollect': 'Batch Collect KPs',
    'dashboard.noQuestions': 'No questions yet, go upload some!',
    'dashboard.deleteConfirm': 'Confirm',
    'dashboard.deleteCancel': 'Cancel',
    'dashboard.filters': 'Multi-dimensional Filters',
    'dashboard.resetFilters': 'Reset All Filters',
    'dashboard.includeMode': 'Include Mode',
    'dashboard.excludeMode': 'Exclude Mode',
    'dashboard.selectAll': 'Select All Visible',
    'dashboard.clearSelection': 'Clear Selection',
    'dashboard.batchInputIds': 'Batch input IDs (U0001.U0002)...',
    'dashboard.batchSelect': 'Batch Select',
    'dashboard.sort.latest': 'Latest',
    'dashboard.sort.earliest': 'Earliest',
    'dashboard.sort.random': 'Random',
    'dashboard.adminConsole': 'Admin Console',
    'dashboard.questionBank': 'Biology Question Bank',
    'dashboard.totalQuestions': 'Total Questions',
    'dashboard.selectedQuestions': 'Selected Questions',
    'dashboard.selected': 'Selected {count} items',
    'dashboard.distribution': 'Selection Distribution',
    'dashboard.totalSelected': 'Total {count} items',
    'dashboard.copyIds': 'Copy IDs',
    'dashboard.generatePaper': 'Generate Paper',
    'dashboard.paperTitle': 'Paper Title',
    'dashboard.paperTitlePlaceholder': 'Enter paper title...',
    'dashboard.generateConfirm': 'Confirm Generate',
    'dashboard.nickname': 'Nickname',
    'dashboard.batchActions': 'Batch Actions',
    'dashboard.inputTag': 'Input tag...',
    'dashboard.addTag': 'Add Tag',
    'dashboard.batchCollectKps': 'Batch Collect KPs',
    'dashboard.filter.field': 'Field',
    'dashboard.filter.difficulty': 'Difficulty',
    'dashboard.filter.source': 'Source',
    'dashboard.filter.type': 'Type',
    'dashboard.filter.uploader': 'Uploader',
    'dashboard.filter.personalTags': 'Personal Tags',
    'dashboard.filter.publicTags': 'Public Tags',
    'dashboard.welcome.subtitle': '{name}, what kind of challenges are you ready to tackle today?',

    // KnowledgeBase
    'kb.title': 'My Knowledge Base',
    'kb.subtitle': 'Manage your personal biology key points',
    'kb.tab.level1': 'Level 1',
    'kb.tab.level2': 'Level 2',
    'kb.tab.level3': 'Level 3',
    'kb.tab.mastered': 'Mastered',
    'kb.tab.summary': 'Summary',
    'kb.search': 'Search key points...',
    'kb.import': 'Batch Import IDs',
    'kb.importPlaceholder': 'Enter IDs, separated by comma or newline',
    'kb.importBtn': 'Import',
    'kb.empty': 'No key points in this level',
    'kb.summary.total': 'Currently {count} knowledge points recorded.',
    'kb.summary.mastered': 'Among them, {count} are fully mastered.',
    'kb.summary.suggestion.improve': 'You have {count} points at Level 1. Suggest improving at least 5 today.',
    'kb.summary.suggestion.good': 'Your knowledge system is solid, keep it up!',
    'kb.summary.ai.loading': 'AI is analyzing your knowledge system...',
    'kb.summary.ai.placeholder': 'Click refresh to generate AI summary',
    'kb.summary.ai.fail': 'AI summary failed, please try again later.',
    'kb.summary.ai.networkError': 'Network error, please check connection.',
    'kb.aiAnalysis': 'AI Analysis Report',
    'kb.distribution': 'Knowledge Distribution',
    'kb.suggestion': "Today's Suggestion",

    // Upload
    'upload.title': 'Upload Biology Question',
    'upload.subtitle': 'Supports OCR and AI auto-organization',
    'upload.step1': 'Upload Question',
    'upload.step2': 'Upload Explanation (Optional)',
    'upload.step3': 'Confirm Info',
    'upload.step4': 'Generate KPs',
    'upload.field': 'Field',
    'upload.source': 'Source',
    'upload.difficulty': 'Difficulty',
    'upload.type': 'Type',
    'upload.content': 'Content',
    'upload.explanation': 'Explanation',
    'upload.submit': 'Submit Question',
    'upload.questionId': 'Question ID',
    'upload.optional': 'Optional',
    'upload.required': 'Required',
    'upload.autoOcr': 'Auto OCR',
    'upload.clickOrDrag': 'Click or drag image',
    'upload.releaseToSelect': 'Release to select',
    'upload.camera': 'Camera',
    'upload.gallery': 'Gallery',
    'upload.remove': 'Remove',
    'upload.generatingKps': 'Generating KPs...',
    'upload.confirmKps': 'Confirm KPs',
    'upload.aiAnalyzing': 'AI Analyzing...',
    'upload.ocrProcessing': 'OCR Processing...',
    'detail.back': 'Back',
    'detail.edit': 'Edit',
    'detail.content': 'Content',
    'detail.answer': 'Answer',
    'detail.noAnswer': 'No Answer',
    'detail.explanation': 'Explanation',
    'detail.noExplanation': 'No Explanation',
    'detail.aiKps': 'AI Knowledge Points',
    'detail.categoryInfo': 'Category Info',
    'detail.notSet': 'Not Set',
    'detail.metadata': 'Metadata',
    'detail.uploader': 'Uploader',
    'detail.uploadTime': 'Upload Time',
    'detail.image': 'Image',
    'detail.notFound': 'Question Not Found',
    'detail.backToBank': 'Back to Bank',
    'detail.unknownUser': 'Unknown User',

    // Enums
    'enum.diff.难题': 'Hard',
    'enum.diff.易错题': 'Tricky',
    'enum.difficulty.难题': 'Hard',
    'enum.difficulty.易错题': 'Tricky',
    'enum.type.概念题': 'Concept',
    'enum.type.计算题': 'Calculation',
    'enum.type.材料题': 'Material',
    'enum.field.生物化学': 'Biochemistry',
    'enum.field.细胞生物学': 'Cell Biology',
    'enum.field.植物学': 'Botany',
    'enum.field.动物学': 'Zoology',
    'enum.field.微生物学': 'Microbiology',
    'enum.field.动物生理学': 'Animal Physiology',
    'enum.field.植物生理学': 'Plant Physiology',
    'enum.field.其他': 'Other',
    'enum.source.猿辅导': 'Yuanfudao',
    'enum.source.汇智启航': 'Huizhi',
    'enum.source.北斗学友': 'Beidou',
    'enum.source.联赛题': 'League',
    'enum.source.国赛题': 'National',
    'enum.source.愿程': 'Yuancheng',
    'enum.source.其他': 'Other',

    // Common
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.redo': 'Redo',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.finish': 'Finish',
    'common.all': 'All',
    'common.none': 'None',

    // Leaderboard
    'leaderboard.title': 'Leaderboard',
    'leaderboard.subtitle': 'Witness the growth of every biology expert',
    'leaderboard.tab.questions': 'Questions',
    'leaderboard.tab.kps': 'Knowledge Points',
    'leaderboard.tab.answers': 'Answers',
    'leaderboard.tab.tokens': 'Tokens',
    'leaderboard.rank': 'Rank',
    'leaderboard.user': 'User',
    'leaderboard.score': 'Score',
    'leaderboard.fullList': 'Full List',
    'leaderboard.activeUsers': '{count} Active Users',
    'leaderboard.anonymous': 'Anonymous User',
    'leaderboard.champion': 'Champion Contributor',
    'leaderboard.runnerUp': 'Runner-up Contributor',
    'leaderboard.thirdPlace': 'Third-place Contributor',
    'leaderboard.unit.question': 'items',
    'leaderboard.unit.kp': 'items',
    'leaderboard.unit.answer': 'times',
    'leaderboard.unit.token': 'tokens',
    'leaderboard.label.questions': 'Questions Uploaded',
    'leaderboard.label.kps': 'KPs Uploaded',
    'leaderboard.label.answers': 'Answers Count',
    'leaderboard.label.tokens': 'Token Usage',
    'leaderboard.noData': 'No leaderboard data yet',
    'leaderboard.role.admin': 'Admin',
    'leaderboard.role.student': 'Member',
    'leaderboard.howToEarn': 'How to earn points?',
    'leaderboard.earn.upload': 'Upload a new question',
    'leaderboard.earn.selected': 'Question selected by others',
    'leaderboard.earn.generate': 'Generate and print a paper',
    'leaderboard.whatIsPoints': 'What are points for?',
    'leaderboard.pointsDesc': 'Points are the unique measure of system contribution.',

    // Answer Page
    'answer.title': 'KP Challenge',
    'answer.subtitle': 'Consolidate memory, conquer difficulties',
    'answer.inputPlaceholder': 'Enter your answer...',
    'answer.submit': 'Submit for Grading',
    'answer.evaluating': 'AI is grading...',
    'answer.pass': 'Congrats! Correct Answer',
    'answer.fail': 'Oops! Incorrect Answer',
    'answer.keepLevel': "I'm still good",
    'answer.next': 'Next Question',
    'answer.evalFail': 'Evaluation failed, please try again',
    'answer.noKps': 'No knowledge points found for answering',
    'answer.progress': 'Progress',

    // Admin
    'admin.title': 'Account Management',
    'admin.subtitle': 'Manage authorized students and registered users',
    'admin.batchImport': 'Batch Import',
    'admin.cancelBatch': 'Cancel Batch',
    'admin.inputStudentId': 'Enter student ID to authorize...',
    'admin.addAuth': 'Add Auth',
    'admin.batchPlaceholder': 'Format: Name:ID. Name:ID.',
    'admin.executeBatch': 'Execute Batch Import',
    'admin.table.idNickname': 'ID / Nickname',
    'admin.table.status': 'Status',
    'admin.table.role': 'Role',
    'admin.table.time': 'Reg/Auth Time',
    'admin.table.action': 'Action',
    'admin.status.registered': 'Registered',
    'admin.status.unregistered': 'Unregistered',
    'admin.role.admin': 'Admin',
    'admin.role.student': 'Student',
    'admin.role.permanent': 'Permanent Admin',
    'admin.action.removeConfirm': 'Remove?',
    'admin.action.yes': 'Yes',
    'admin.action.no': 'No',
    'admin.noData': 'No account data',
    'admin.loading': 'Loading admin data...',
    'admin.birthday.title': 'Birthday Theme',
    'admin.birthday.subtitle': 'Configure site-wide birthday mode',
    'admin.birthday.slogan': 'Birthday Slogan',
    'admin.birthday.placeholder': 'Enter birthday slogan...',
    'admin.qidan.title': 'Qidan Purple Theme',
    'admin.qidan.subtitle': 'Configure site-wide Qidan mode',
    'admin.qidan.slogan': 'Custom Slogan',
    'admin.qidan.placeholder': 'Enter custom slogan...',
    'admin.saveConfig': 'Save Config',
    'admin.enabled': 'Enabled',
    'admin.disabled': 'Disabled',
    'admin.permanentAdminError': 'This account is a permanent admin and cannot be changed.',
    'admin.permanentAdmin.editId': 'Modify Permanent Admin Student ID',
    'admin.permanentAdmin.newIdPlaceholder': 'Enter new student ID...',
    'admin.permanentAdmin.updateBtn': 'Update ID',
    'admin.permanentAdmin.confirmTitle': 'Confirm ID Change?',
    'admin.permanentAdmin.confirmDesc': 'After modification, you will need to log in again with the new student ID.',
    'admin.demoError': 'Cannot save settings in demo mode',
    'admin.saveSuccess': 'Settings updated!',
    'admin.saveFail': 'Save failed',
    'admin.batchSuccess': 'Batch import successful!',
    'admin.batchFail': 'Import failed, please check format.',
    'admin.addFail': 'Add failed, please check network or Firebase config.',

    // Edit Question
    'edit.title': 'Edit Question Info',
    'edit.subtitle': 'EDIT QUESTION',
    'edit.uploaderInfo': 'Uploaded by {uploader} on {date}',
    'edit.backToBank': 'Back to Bank',
    'edit.imagePreview': 'Image Preview',
    'edit.noImage': 'No image for this question',
    'edit.ocrIndex': 'OCR Content (Search Index)',
    'edit.ocrPlaceholder': 'OCR text will appear here...',
    'edit.fieldLabel': 'Field (Multi-select)',
    'edit.sourceLabel': 'Source',
    'edit.sourceDetailLabel': 'Source Detail',
    'edit.sourceDetailPlaceholder': 'e.g., 2024 Haidian Midterm Q15',
    'edit.difficultyLabel': 'Difficulty (Multi-select)',
    'edit.typeLabel': 'Type',
    'edit.publicTagsLabel': 'Public Tags (Comma separated)',
    'edit.publicTagsPlaceholder': 'e.g., Required 1, Key, Tricky',
    'edit.answerLabel': 'Answer',
    'edit.answerPlaceholder': 'Enter correct answer...',
    'edit.explanationLabel': 'Explanation',
    'edit.explanationPlaceholder': 'Enter explanation process...',
    'edit.saveBtn': 'Save Changes',
    'edit.loading': 'Loading question data...',
    'edit.notExist': 'Question does not exist',
    'edit.noPermission': 'No permission to edit this question',
    'edit.loadFail': 'Load failed',
    'edit.saveSuccessDemo': 'Demo mode: Changes simulated saved.',

    // Knowledge Base Extra
    'kb.level.masteredTitle': 'Mastered Knowledge Points',
    'kb.level.masteredDesc': 'List of knowledge points you have fully mastered',
    'kb.level.searchPlaceholder': 'Search knowledge points...',
    'kb.level.allFields': 'All Fields',
    'kb.level.newTab': 'Open in new tab',
    'kb.level.exportPdf': 'Print / Export PDF',
    'kb.level.levelName': 'Level {level} Knowledge Points',
    'kb.level.levelDesc': 'Knowledge points currently at level {level}',
    'kb.level.batchImportTitle': 'Batch Import IDs',
    'kb.level.batchImportPlaceholder': 'Enter IDs (e.g., U0001 U0002)',
    'kb.level.import': 'Import',
    'kb.level.title': 'Knowledge Level',
    'kb.level.printTitle': 'Knowledge List',
    'kb.level.noMatch': 'No matching knowledge points',
    'kb.level.startAnswering': 'Start Answering',
    'kb.printCount': 'Count',
    'kb.printVersion': 'Version',
    'kb.printVersionA': 'KP Only',
    'kb.printVersionB': 'KP + Answer',
    'kb.printTooltip': 'Open in new tab for better printing',
    'kb.exportTooltip': 'Print / Export PDF',
    'kb.batchImportTitle': 'Batch Import IDs',
    'kb.batchImportPlaceholder': 'Enter IDs (e.g., U0001 U0002)',
    'kb.batchImportBtn': 'Import',
    'kb.printTitle': 'Knowledge List',
    'kb.printDate': 'Generated Date',
    'kb.printMasteredTitle': 'Mastered Knowledge List',
    'kb.summary.distribution': 'Knowledge Distribution Analysis',
    'kb.summary.report': 'Overall Analysis Report',
    'kb.summary.weakness': 'Weakness Suggestions',
    'kb.summary.strengthen': 'Strengthen',
    'kb.summary.progress': 'Learning Progress',
    'kb.summary.level1': 'Level 1 (To Learn)',
    'kb.summary.level2': 'Level 2 (Reviewing)',
    'kb.summary.level3': 'Level 3 (Sprinting)',
    'kb.summary.level4': 'Mastered',

    // Upload Extra
    'upload.kpExists': 'Knowledge point "{title}" already exists in your library.',
    'upload.kpCollected': '"{title}" has been collected to your library!',
    'upload.kpCollectFail': 'Collection failed, please try again.',
    'upload.duplicateQuestion': 'Duplicate question detected, redirecting to details...',
    'upload.ocrFail': 'Image processing or AI recognition failed, please enter manually.',
    'upload.noImageError': 'Please upload question text image first',
    'upload.noContentError': 'Question content cannot be empty.',
    'upload.noKpError': 'Please confirm at least one knowledge point.',
    'upload.tooManyKpsError': 'No more than 3 knowledge points.',
    'upload.submitSuccess': 'Question uploaded successfully!',
    'upload.submitFail': 'Submission failed, please try again.',
    'upload.addKp': 'Add KP',
    'upload.aiHint': 'If you want to upload an explanation, please upload it together before clicking AI analysis',
    'kb.level.confirmMaster': 'Confirm Mastered',
    'kb.level.questionId': 'Question ID',
    'paper.mode.paper': 'Paper Mode',
    'paper.mode.answer': 'Answer Mode',
    'paper.mode.explanation': 'Explanation Mode',
    'paper.newTab': 'Open in New Tab',
    'paper.printBtn': 'Print / Export',
    'paper.backToSetup': 'Back to Setup',
    'paper.printTip': 'Tip: Please check "Background Graphics" in print settings for best results',
    'paper.total': 'items',
    'paper.countLabel': 'Count',
    'paper.title': 'Paper Generator',
    'paper.subtitle': 'Generate professionally formatted papers from selected questions',
    'paper.status.title': 'Status',
    'paper.status.ready': '{count} items selected, ready to go',
    'paper.status.empty': 'No items selected',
    'paper.status.continue': 'Continue',
    'paper.status.goSelect': 'Go Select',
    'paper.inputTitle': 'Main Title',
    'paper.inputTitlePlaceholder': 'e.g., 2024 Biology Final Mock Test',
    'paper.layoutOptions': 'Layout Options',
    'paper.option.autoNumber': 'Auto Numbering',
    'paper.option.studentInfo': 'Student Info Bar',
    'paper.option.a4Size': 'A4 Paper Size',
    'paper.previewExport': 'Preview & Export',
    'paper.enterPreview': 'Enter Preview Mode',
    'paper.tipTitle': 'Tips',
    'paper.tipDesc': 'Generated papers will automatically include content, source, etc. You can choose different modes (Paper/Answer/Explanation) for printing.',
    'paper.selectedCount': 'Selected Items',
    'paper.noContent': 'No content available',
    'paper.noAnswer': 'No answer available',
    'paper.noExplanation': 'No explanation available',
    // Layout
    'layout.updateNicknameFail': 'Failed to update nickname, please try again.',
    'layout.fullscreen.exit': 'Exit Fullscreen',
    'layout.fullscreen.enter': 'Fullscreen',
    'layout.viewMode.title': 'View Mode',
    'layout.viewMode.auto': 'Auto',
    'layout.viewMode.mobile': 'Mobile',
    'layout.viewMode.desktop': 'Desktop',
    'layout.nickname.placeholder': 'Set nickname...',
    'layout.status.online': 'Online',
    'layout.feedback': 'Feedback',
    'layout.demoMode.title': 'Demo Mode',
    'layout.demoMode.desc': 'Data will not be saved',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
